import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Aarush Katta
 *
 */
public final class RSSReader {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSReader() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title</title>
     * </head> <body>
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <table border="1">
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel")
                : "" + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        String title = "Empty Title", link = "", desc = "No Description";

        // Get title
        String s = channel.child(getChildElement(channel, "title")).child(0).label();
        if (!s.isEmpty()) {
            title = s;
        }

        // get link
        link = channel.child(getChildElement(channel, "link")).child(0).label();

        // get description
        s = channel.child(getChildElement(channel, "description")).child(0).label();
        if (!s.isEmpty()) {
            desc = s;
        }

        out.println("<html><head><title>" + title + "</title></head><body><h1><a href=\""
                + link + "\">" + title + "</a></h1><p>" + desc
                + "</p><table border=\"1\"><tr><th>Date</th>"
                + "<th>Source</th><th>News</th></tr>");
    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table>
     * </body> </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("</table></body></html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        // loop through all children
        int a = -1, i = 0;
        while (i < xml.numberOfChildren()) {
            if (xml.child(i).label().equals(tag)) {
                // set index to a and force exit the while loop
                a = i;
                i = xml.numberOfChildren();
            }
            i++;
        }
        return a;
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item")
                : "" + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        String pubDate = "No date available", source = "No source available",
                sourceLink = "", title = "", description = "No title available",
                link = "";

        // get publication date
        int i = 0;
        i = getChildElement(item, "pubDate");
        if (i != -1) {
            pubDate = item.child(i).child(0).label();
        }

        // get source and source link
        i = getChildElement(item, "source");
        if (i != -1) {
            source = item.child(i).child(0).label();
            if (item.child(i).hasAttribute("url")) {
                sourceLink = item.child(i).attributeValue("url");
            }
        }

        // get title
        i = getChildElement(item, "title");
        if (i != -1) {
            title = item.child(i).child(0).label();
        }

        // get description
        i = getChildElement(item, "description");
        if (i != -1) {
            description = item.child(i).child(0).label();
        }

        // get link
        i = getChildElement(item, "link");
        if (i != -1) {
            link = item.child(i).child(0).label();
        }

        // if there is no title, set it to description
        if (title.isEmpty()) {
            title = description;
        }

        // add source link if it exists
        if (!sourceLink.isEmpty()) {
            source = "<a href=\"" + sourceLink + "\">" + source + "</a>";
        }

        // add link to title if it exists
        if (!link.isEmpty()) {
            title = "<a href=\"" + link + "\">" + title + "</a>";
        }

        out.println("<tr><td>" + pubDate + "</td><td>" + source + "</td><td>" + title
                + "</td></tr>");
    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        // get user inputed rss file
        out.println("Enter a link to an RSS feed: ");
        String link = in.nextLine();

        // make xml
        XMLTree xml = new XMLTree1(link);

        // assert xml file is proper rss
        assert xml.label().equals("rss") : "Root is not rss tag";
        assert xml.hasAttribute("version") && xml.attributeValue("version").equals("2.0")
                : "RSS version is not 2.0";

        // set channel to root
        int c = getChildElement(xml, "channel");
        xml = xml.child(c);

        // print header
        outputHeader(xml, out);

        // loop over every child, check if it's item and process the item
        for (int i = 0; i < xml.numberOfChildren(); i++) {
            XMLTree t = xml.child(i);
            if (t.label().equals("item")) {
                processItem(t, out);
            }
        }

        // print footer
        outputFooter(out);

        // close input and output
        in.close();
        out.close();
    }

}
